---
title: "Models & Results"
author: "Dayne Filer"
date: "6/2/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages & needed data:

```{r,warning=FALSE,message=FALSE,results='hide'}
library(kassotis2020)
library(data.table)
data(ph1data)
data(ph3data)
data(ph3zscr)
data(chemData)
data(controls)
data(janesick)
```

```{r}
baseline <- evalPred(controls$cellActive, controls$litActive)
baseline$metrics
```


```{r}
## PhI assays
ph1 <- c("ATG_PPRE_CIS",                   "ATG_PPARg_TRANS",     
         "NVS_NR_hPPARg",                  "NCGC_PPARg_Agonist",    
         "NCGC_GR_Agonist",                "NVS_NR_hGR", 
         "ATG_GR_TRANS",                   "ATG_GRE_CIS",         
         "ATG_LXRa_TRANS",                 "ATG_LXRb_TRANS",        
         "NCGC_LXR_Agonist",               "ATG_DR4_LXR_CIS", 
         "ATG_C_EBP_CIS",                  "ATG_SREBP_CIS",       
         "ATG_RXRa_TRANS",                 "NCGC_RXRa_Agonist")

## PhIII assays
ph3 <- c("ATG_PPRE_CIS_up",                "ATG_PPARg_TRANS_up",  
         "TOX21_PPARg_BLA_Agonist_ratio",  "NVS_NR_hPPARg",          
         "OT_PPARg_PPARgSRC1_0480",        "OT_PPARg_PPARgSRC1_1440", 
         "ATG_PPARa_TRANS_up",             "NVS_NR_hPPARa",
         "ATG_PPARd_TRANS_up",             "TOX21_PPARd_BLA_agonist_ratio",
         "TOX21_GR_BLA_Agonist_ratio",     "NVS_NR_hGR", 
         "ATG_GR_TRANS_up",                "ATG_GRE_CIS_up",
         "ATG_LXRa_TRANS_up",              "ATG_LXRb_TRANS_up",
         "ATG_DR4_LXR_CIS_up",             "ATG_C_EBP_CIS_up", 
         "ATG_SREBP_CIS_up",               "ATG_RXRa_TRANS_up",
         "TOX21_RXR_BLA_Agonist_ratio",    "OT_NURR1_NURR1RXRa_0480",
         "OT_NURR1_NURR1RXRa_1440",        "ATG_RXRb_TRANS_up",
         "ATG_RXRg_TRANS2_up",             "ATG_PXRE_CIS_up",
         "ATG_PXR_TRANS_up",               "NVS_NR_hPXR",
         "ACEA_AR_antagonist_80hr",        "ATG_AR_TRANS_up",
         "NVS_NR_cAR",                     "NVS_NR_hAR", 
         "NVS_NR_rAR",                     "OT_AR_ARELUC_AG_1440",
         "OT_AR_ARSRC1_0480",              "OT_AR_ARSRC1_0960", 
         "TOX21_AR_BLA_Antagonist_ratio", 
         "TOX21_AR_LUC_MDAKB2_Antagonist_10nM_R1881",
         "ATG_CAR_TRANS_up",               "NVS_NR_hCAR_Agonist",
         "TOX21_CAR_Agonist",              "ATG_FXR_TRANS_up",
         "ATG_IR1_CIS_up",                 "NVS_NR_hFXR_Agonist", 
         "OT_FXR_FXRSRC1_0480",            "OT_FXR_FXRSRC1_1440",
         "TOX21_FXR_BLA_agonist_ratio",    "ATG_THRa1_TRANS_up",
         "ATG_THRb_TRANS2_up",             "NVS_NR_hTRa_Antagonist",
         "TOX21_TR_LUC_GH3_Antagonist",    "ATG_DR5_CIS_up",
         "ATG_RARa_TRANS_up",              "NVS_NR_hRARa_Agonist",
         "TOX21_RAR_LUC_Agonist",          "ATG_RARb_TRANS_up",
         "ATG_RARg_TRANS_up",              "BSK_CASM3C_LDLR_up",
         "NVS_ENZ_hIGF1R",                 "NVS_ENZ_hIGF1R_Activator", 
         "NVS_ENZ_hInsR",                  "NVS_ENZ_hInsR_Activator")

## 8-slice model used in Janesick et al. w/ phI assays
et1 <- list(slices = list(PPRE = ph1[1],      PPARg = ph1[2:4], 
                          GR   = ph1[5:8],    LXR   = ph1[9:11], 
                          LXRE = ph1[12],     CEBP = ph1[13],
                          SREBP = ph1[14],    RXRa =  ph1[15:16]), 
            weights = c(1, 1, 1, 1, 1, 1, 1, 1))

## 8-slice model used in Janesick et al. w/ phIII assays
et3 <- list(slices = list(PPRE  = ph3[1],     PPARg = ph3[2:4], 
                          GR    = ph3[11:14], LXR   = ph3[15:16], 
                          LXRE  = ph3[17],    CEBP  = ph3[18],
                          SREBP = ph3[19],    RXRa  = ph3[20:21]), 
            weights = c(1, 1, 1, 1, 1, 1, 1, 1))
```

We can then calculate the ToxPi scores and look at prediction metrics.

```{r}
et1Res <- calculateToxpi(ph1data, et1)
et3Res <- calculateToxpi(ph3data, et3)
et3AdZ <- calculateToxpi(ph3data + cbind(ph3zscr, ph3zscr), et3)
```

```{r}
smry <- list(evalPred(controls$cellActive, controls$litActive),
             evalPred(et1Res[janesick$code, "Score"], janesick$cellActive),
             evalPred(et3Res[janesick$code, "Score"], janesick$cellActive),
             evalPred(et3AdZ[janesick$code, "Score"], janesick$cellActive),
             evalPred(et3Res[controls$code, "Score"], controls$cellActive),
             evalPred(et3AdZ[controls$code, "Score"], controls$cellActive),
             evalPred(et3Res[controls$code, "Score"], controls$litActive),
             evalPred(et3AdZ[controls$code, "Score"], controls$litActive))
smryTbl <- as.data.table(t(sapply(smry, '[[', "metrics")))
smryTbl[ , ToxCast := c(NA, "PhI", rep("PhIII", 6))]
smryTbl[ , ControlSet := c(NA, rep("Janesick", 3), rep("Kassotis", 4))]
smryTbl[ , ControlType := c(NA, rep("Cell", 5), rep("Literature", 2))]
smryTbl[ , ZScore := c(NA, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE)]
setcolorder(smryTbl, c("ToxCast", "ControlSet", "ControlType", "ZScore"))
smryTbl
```


```{r,include=FALSE,eval=FALSE}

## 11-slice model with expanded assay coverage
# el3 <- list(slices = list(PPAR = ph3[1:10],   GR  = ph3[11:14],
#                           LXR  = ph3[15:17],  RXR = ph3[20:25],
#                           PXR  = ph3[26:28],  AR  = ph3[29:38],
#                           CAR  = ph3[39:41],  FXR = ph3[42:47],
#                           TR   = ph3[48:51],  RAR = ph3[52:57],
#                           OTHR = ph3[c(18, 19, 58:62)]),
#             weights = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1))

## For efficient storage, the z-scores are not duplicated for the Emax values;
## first, duplicate the ph3zscr matrix for the Emax values
# ph3zscr <- cbind(ph3zscr, ph3zscr)
# ph3adj <- ph3data
# ph3adj[ph3zscr <= 2] <- 0 
# res2 <- calculateToxpi(ph3adj + ph3zscr, mdl2)
# rankPlot(res2,
#          posChems = controls[(litActive), code],
#          negChems = controls[!(litActive), code])
# calculateAUC(res2[controls$code, "Score"], controls$litActive)
# mdl3 <- mdl2
# emax <- mdl3$slices
# names(emax) <- paste0("e", names(emax))
# emax <- lapply(emax, paste0, "_emax")
# mdl3$slices <- c(mdl3$slices, emax)
# mdl3$weights <- c(mdl3$weights, mdl3$weights)
# res3 <- calculateToxpi(ph3adj + ph3zscr, mdl3)
# calculateAUC(res3[controls$code, "Score"], controls$litActive)
```



